"""Create profile initial modelling

Revision ID: 592f0a114a5e
Revises: efcf3711d875
Create Date: 2016-11-15 00:21:59.040192

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '592f0a114a5e'
down_revision = 'efcf3711d875'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_ip', sqlalchemy_utils.types.ip_address.IPAddressType(length=50), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_ip', sqlalchemy_utils.types.ip_address.IPAddressType(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('neighborhood', sa.String(length=200), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], name=op.f('fk_profile_created_by_user_id_user')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], name=op.f('fk_profile_updated_by_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile'))
    )
    op.create_index(op.f('ix_profile_city'), 'profile', ['city'], unique=False)
    op.create_index(op.f('ix_profile_created'), 'profile', ['created'], unique=False)
    op.create_index(op.f('ix_profile_created_by_user_id'), 'profile', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_profile_created_ip'), 'profile', ['created_ip'], unique=False)
    op.create_index(op.f('ix_profile_email'), 'profile', ['email'], unique=False)
    op.create_index(op.f('ix_profile_neighborhood'), 'profile', ['neighborhood'], unique=False)
    op.create_index(op.f('ix_profile_updated'), 'profile', ['updated'], unique=False)
    op.create_index(op.f('ix_profile_updated_by_user_id'), 'profile', ['updated_by_user_id'], unique=False)
    op.create_index(op.f('ix_profile_updated_ip'), 'profile', ['updated_ip'], unique=False)
    op.create_index(op.f('ix_profile_uuid'), 'profile', ['uuid'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_uuid'), table_name='profile')
    op.drop_index(op.f('ix_profile_updated_ip'), table_name='profile')
    op.drop_index(op.f('ix_profile_updated_by_user_id'), table_name='profile')
    op.drop_index(op.f('ix_profile_updated'), table_name='profile')
    op.drop_index(op.f('ix_profile_neighborhood'), table_name='profile')
    op.drop_index(op.f('ix_profile_email'), table_name='profile')
    op.drop_index(op.f('ix_profile_created_ip'), table_name='profile')
    op.drop_index(op.f('ix_profile_created_by_user_id'), table_name='profile')
    op.drop_index(op.f('ix_profile_created'), table_name='profile')
    op.drop_index(op.f('ix_profile_city'), table_name='profile')
    op.drop_table('profile')
    ### end Alembic commands ###
