"""Add relationship between profile and user

Revision ID: e38590e7f6ca
Revises: 592f0a114a5e
Create Date: 2016-11-15 00:34:51.879975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e38590e7f6ca'
down_revision = '592f0a114a5e'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_profile_user_id'), 'profile', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_profile_user_id_user'), 'profile', 'user', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_profile_user_id_user'), 'profile', type_='foreignkey')
    op.drop_index(op.f('ix_profile_user_id'), table_name='profile')
    op.drop_column('profile', 'user_id')
    ### end Alembic commands ###
