"""teste

Revision ID: efcf3711d875
Revises: fd7e42eb6197
Create Date: 2016-11-12 04:38:38.425314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efcf3711d875'
down_revision = 'fd7e42eb6197'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_', sa.String(length=200), nullable=True))
    op.alter_column('user', 'uuid',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.drop_column('user', 'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.alter_column('user', 'uuid',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.drop_column('user', 'password_')
    ### end Alembic commands ###
